[[mixers]]
# servo
bind_ctrl_group_id = 0
output_channel_idx = 0
mode = "PluseWidth"

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 3

[mixers.list.scaler]
scale_p = 0.5
scale_n = 0.5
offset = 1500
min = 1000
max = 2000

[[mixers]]
# motor
bind_ctrl_group_id = 0
output_channel_idx = 1
mode = "PulseWidth"

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 2

[mixers.list.scaler]
scale_p = 0.5
scale_n = 0.5
offset = 1500
min = 1000
max = 2000
