[package]
name = "rust_pilot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpos = {path = "./rpos"}
gz = { version = "0.7.4", features = ["harmonic"] }