[[mixers]]
bind_ctrl_group_id = 0
output_channel_idx = 0

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 0

[mixers.list.scaler]
scale_p = 1.0
scale_n = 1.0
offset = 0.0
min = -100.0
max = 100.0

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 1

[mixers.list.scaler]
scale_p = -1.0
scale_n = -1.0
offset = 0.0
min = -100.0
max = 100.0

[[mixers]]
bind_ctrl_group_id = 0
output_channel_idx = 1

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 0

[mixers.list.scaler]
scale_p = -1.0
scale_n = -1.0
offset = 0.0
min = -100.0
max = 100.0

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 1

[mixers.list.scaler]
scale_p = 1.0
scale_n = 1.0
offset = 0.0
min = -100.0
max = 100.0

[[mixers]]
bind_ctrl_group_id = 0
output_channel_idx = 2

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 0

[mixers.list.scaler]
scale_p = 1.0
scale_n = 1.0
offset = 0.0
min = -100.0
max = 100.0

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 1

[mixers.list.scaler]
scale_p = 1.0
scale_n = 1.0
offset = 0.0
min = -100.0
max = 100.0

[[mixers]]
bind_ctrl_group_id = 0
output_channel_idx = 3

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 0

[mixers.list.scaler]
scale_p = -1.0
scale_n = -1.0
offset = 0.0
min = -100.0
max = 100.0

[[mixers.list]]
ctrl_group_id = 0
ctrl_channel_idx = 1

[mixers.list.scaler]
scale_p = -1.0
scale_n = -1.0
offset = 0.0
min = -100.0
max = 100.0