[build]
target = ["x86_64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf"]

[target.x86_64-unknown-linux-gnu]
linker = "cc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"


