name: BasicBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update apt
      run: sudo apt-get update
    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.4.1
      with:
        packages: libudev-dev
        version: 1.0
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
    - name: submodule
      run: git submodule update --init
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_TEST_THREADS=1 cargo test --verbose
